# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib ojoutils, .registration = TRUE
NULL

count_interval_ <- function(stream, start, end, end_plus_one, date_name, count_name, by, inclusive) .Call(wrap__count_interval_, stream, start, end, end_plus_one, date_name, count_name, by, inclusive)

# nolint end
